VUmeterDisplayConfiguration:
    DisplayerClass: "devidin.net.yavumeter.display.ConsoleDisplayer"
    
SoundCardHelperConfiguration:
    AudioFormat : {sampleRate: 16000, sampleSizeInBits: 8, channels : 2, signed : true, bigEndian : true}
    
ConsoleDisplayerConfiguration:
    width: 132
    maxAmplitude: 128
    displayMethod: "display"
    
JavaFXDisplayerConfiguration:
        totalWindowWidth: 800
        totalWindowHeight: 600