# GraphicalDisplayerParameters.yml
referenceWidth: 1235
referenceHeight: 630
#############################################
background: "mcintosh"
color: "blue"
color: "white"
color: "yellow"
color: "green"

background: "nad"
color: "white"
color: "blue"

fileType: "jpg"

foregroundFileName: "foreground.png"

needleRed: 255
needleGreen: 0
needleBlue: 0
needleWidth: 2
needleShadow: true

#############################################
# test cases
#############################################
# top center ok
xC: 618
yC: -300
xMin: 60
yMin: 400
xMax: 1188
yMax: 400

# left center ok
xC: -100
yC: 315
xMin: 1100
yMin: 600
xMax: 1100
yMax: 0
# right center ok
xC: 1435
yC: 315
xMin: 100
yMin: 600
xMax: 100
yMax: 100
# left horizontal ok
xC: -100000
yC: 315
xMin: 1100
yMin: 0
xMax: 1100
yMax: 600

# right horizontal ok
xC: 1000000
yC: 315
xMin: 100
yMin: 600
xMax: 100
yMax: 100
# right horizontal ok
xC: 1000000
yC: 315
xMin: 100
yMin: 600
xMax: 100
yMax: 100


# bottom Veritcal ok
xC: 618
yC: +100000
xMin: 60
yMin: 100
xMax: 1188
yMax: 100

# top vertical ok
xC: 618
yC: -1000000
xMin: 60
yMin: 600
xMax: 1188
yMax: 600
#############################################
# test cases end
#############################################
# bottom center ok <<<<<<<<<<<<<<<<<<<<<<<<<<<<
xC: 618
yC: 1000
xMin: 60
yMin: 237
xMax: 1188
yMax: 237
# bottom center ok <<<<<<<<<<<<<<<<<<<<<<<<<<<<
