# GraphicalDisplayerParameters.yml
referenceWidth: 1235
xC: 618
yC: 800
xMin: 60
yMin: 237
xMax: 1188

color: "blue"
background: "mcintosh"
fileType: "jpg"

needleRed: 0
needleGreen: 0
needleBlue: 0


