# GraphicalDisplayerParameters.yml
referenceWidth: 1235
referenceHeight: 630
xC: 618
yC: 1000
xMin: 60
yMin: 237
xMax: 1188

color: "blue"
background: "mcintosh"
fileType: "jpg"

needleRed: 0
needleGreen: 0
needleBlue: 0


