# GraphicalDisplayerParameters.yml
referenceWidth: 1235
referenceHeight: 630
#############################################
# top center ok
xC: 618
yC: -100
xMin: 60
yMin: 600
xMax: 1188
yMax: -1
# left center ok
xC: -100
yC: 315
xMin: 1100
yMin: 0
xMax: -1
yMax: 600
# bottom Veritcal ok
xC: 618
yC: +1000000

xMin: 60
yMin: 237

xMax: 1188
yMax: -1
# top vertical ok
xC: 618
yC: -1000000

xMin: 60
yMin: 600

xMax: 1188
yMax: -1
# left horizontal ok
xC: -1000000
yC: 315
xMin: 1100
yMin: 0
xMax: -1
yMax: 600
# right horizontal ko
xC: 1000000
yC: 315
xMin: 30
yMin: 0
xMax: -1
yMax: 600
# right center ok
xC: 1135
yC: 315
xMin: 100
yMin: 0
xMax: -1
yMax: 600
# bottom center ok
xC: 618
yC: 1000
xMin: 60
yMin: 237
xMax: 1188
yMax: -1
#############################################
color: "blue"
background: "mcintosh"
fileType: "jpg"

needleRed: 0
needleGreen: 0
needleBlue: 0


