# GraphicalDisplayerParameters.yml
referenceWidth: 1235
referenceHeight: 630
#############################################
maxDownSpeed: 0.5
maxUpSpeed: 4.0
#############################################
background: "mcintosh"
color: "blue"

fileType: "jpg"
foregroundFileName: "rectangle foreground.png"
#logoFileName: "logo.png"
preserveAspectRatio: true

needleRed: 0
needleGreen: 0
needleBlue: 0
needleWidth: 2
needleShadow: true
needleShadowOffsetX: 20
needleShadowOffsetY: -5

backgroundRed: 0
backgroundGreen: 0
backgroundBlue: 0

xC: 618
yC: 900
xMin: 75
yMin: 260
xMax: 1170
yMax: 260
