# GraphicalDisplayerParameters.yml
referenceWidth: 1235
referenceHeight: 630
#############################################
color: "blue"
background: "mcintosh"
fileType: "jpg"

needleRed: 200
needleGreen: 0
needleBlue: 0
needleWidth: 2
needleShadow: true

#############################################
# bottom Veritcal 
xC: 618
yC: +1000000

xMin: 60
yMin: 237

xMax: 1188
yMax: -1
# top vertical 
xC: 618
yC: -1000000

xMin: 60
yMin: 600

xMax: 1188
yMax: -1
# left horizontal 
xC: -1000000
yC: 315
xMin: 1100
yMin: 0
xMax: -1
yMax: 600
# right horizontal 
xC: 1000000
yC: 315
xMin: 30
yMin: 0
xMax: -1
yMax: 600



# left center 
xC: -100
yC: 315

xMin: 1100
yMin: 0

xMax: 1100
yMax: 600
# right center 
xC: 1135
yC: 315
xMin: 100
yMin: 0
xMax: 100
yMax: 600

# top center 
xC: 618
yC: -300
xMin: 60
yMin: 400
xMax: 1188
yMax: 400

# bottom center ok
xC: 618
yC: 1000
xMin: 60
yMin: 237
xMax: 1188
yMax: 237




