#displayerClass: "devidin.net.yavumeter.display.console.ConsoleDisplayer"
displayerClass: "devidin.net.yavumeter.display.graphical.GraphicalDisplayer"
bufferSize: 1600
# wait time between calls
intervalMs: 15

mixerName: "VoiceMeeter Output (VB-Audio Vo"

#mixerID: 8
#lineID: 0

 # rms/avg
loudnessMode: "RMS"

 # SQUAREROOT,SQUARE,LINEAR, LOG (,EXP - not recommended)
viewMode: "LOG"
